//$Id: ground_unit.idl,v 1.13 2025/07/16 08:34:30 cvswxc Exp $

#ifndef GROUND_UNIT_INCLUDED
#define GROUND_UNIT_INCLUDED
#include <general_unit.idl>
module Ground_Unit 
{
		
		//2D位姿
		struct Pose2D
		{
			float x;
			float y;
			float yaw;
		};
		
		//速度
		struct Speed2D 
		{
			float leanerVel;
			float angularVel;
		};
		
		//地面单元信息
		struct GroundUnitInfo
		{
			Unit::UnitInfo info;
			Unit::UnitRole role;
			Speed2D speed;
			Pose2D pose;
		};
		
		//2D点坐标
		struct Point2D
		{
			float x;
			float y;
		};
		
		//2D点陷阱数据
		struct TrapPoint2D
		{
			Point2D point;
			float radius;
		};
		
		
		//二维点序列
		typedef sequence<Point2D> TaskPath;
		
		//二维点陷阱序列
		typedef sequence<TrapPoint2D> TrapPointSeq;
		
 
  interface rpc:Unit::rpc
	{		
		//*******************  get information  *******************
		
		
		//Get current UAV speed 
		Speed2D getCurrentSpeed();
		
		//Get Current UAV 2D Pose 
		Pose2D getCurrentPose();
		
		//Get Current UAV Unit Info 
		GroundUnitInfo getCurrentInfo();
		
		//*******************Control API's of UAV *******************
		
		/*前车向后车发送位姿
			1.参数：
				1)info：前车当前车辆信息
			2.执行内容：
				1)将目标位置放入缓冲区或直接覆盖当前目标？
		*/
		boolean sendVehicleInfo(in GroundUnitInfo info);
			
		/*向Leader汇报陷阱，仅Leader响应
			1.参数：
				1)trap: 陷阱区域
			2.执行内容：
				1)Leader广播陷阱，并与控制台同步，OP_AddTrap
		*/
		boolean reportTrap(in TrapPoint2D trap);
		
		/*清除所有陷阱，控制台调用********************用于测试********************
			1.参数：
			2.执行内容：
				1)清楚当前车辆所有陷阱
		*/
		boolean clearTraps();
		
		/*获取所有陷阱
			1.参数：
			2.执行内容：
				1)返回当前车辆所有陷阱点
		*/
		TrapPointSeq getTraps();
		
		/*设置陷阱点
			1.参数：
				1)trap：陷阱点
			2.执行内容：将点加入trap数组中，用于避让，不区分模式
		*/
		boolean setTrapPoint(in TrapPoint2D trap);
		
		/*设置车辆的目标队列
			1.参数：
				1)path：轨迹点
			2.执行内容：
				1)设置车辆的目标队列，仅在VMM_FW_Track模式下生效
		*/
		boolean setTrack(in TaskPath track);

		/*设置任务路径
			执行内容：
				1)重置任务路径
		*/
		boolean setTaskPath(in TaskPath path);
		
		/*设置目标点
			执行内容：
				1)重置目标点
		*/
		boolean setTaskPoint(in Point2D point);

	};
};
#endif

/*

2025-7-16 wxc  将飞机和车都有的setRearVehicles移动到unit里面

2025-7-10 wxc 将MoveActionType ActionSeq相关的共性数据和操作下沉到General_Unit模块中 

2025-7-9 wxc 将接口统一用API替代

2025-7-7 1)统一将Sequence --> Seq 


2020年4月26日
	1)增加类型 enum VehicleMinorMode
	2)增加函数 boolean setMinorMode(in VehicleMinorMode minorMode);
	3)函数声明改动
			boolean reportDeadRearVehicle(in UnitID uid)
	  改为：
			boolean reportDeadVehicle(in UnitID uid, in string details);
	4)增加函数
			boolean setTrack(in TaskPath path);
2020年5月8日
	1)增加函数 boolean setTrapPoint(in Point2D trap, in float radius);

2020年5月12日
	1)增加类型 struct TrapPoint2D
	2)函数声明改动
			boolean reportDeadVehicle(in UnitID uid, in string details);
	  改为：
			boolean reportDeadVehicle(in UnitID uid, in string details, in TrapPoint2D trap);
	3)函数声明改动
			boolean setTrapPoint(in Point2D trap, in float radius);
	  改为：
			boolean setTrapPoint(in TrapPoint2D trap);
2020年5月13日
	1)函数声明改动
			boolean reportDeadVehicle(in UnitID uid, in string details, in TrapPoint2D trap);
	  改为：
			boolean reportDeadVehicle(in UnitID uid, in string details);
	2)增加类型
			typedef sequence<TrapPoint2D> TrapPointSequence;
	3)增加函数
			boolean reportTrap(in TrapPoint2D trap);
	4)增加函数
			TrapPointSequence getTraps();
	5)增加函数
			boolean clearTraps();
*/